# Generated by Django 3.2.18 on 2023-04-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
