# Generated by Django 3.2.18 on 2023-04-16 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_topic_topiccategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='topiccategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.topic')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
