# Generated by Django 3.2.18 on 2023-04-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_auto_20230416_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Topic Categories'},
        ),
    ]
